fn main() {
    // std::process::exit(1);
    std::process::abort(); // This will cause the process to exit with a failure status
}
